### ISSUE TITLE
Show/hide header row

### ISSUE THREAD

**Issue by firecat53** [TabViewer/tabview#11]

**Comment by ddofborg** [comment]
Is it possible to use this with a shortcut? That would be helpful :)

**Comment by ddofborg** [comment]
I mean being able to hide a column/row from the view. Like you would in
Excel. In case your CSV has some rows/columns you don't want to see.

**Comment by firecat53** [comment]
Ah, I see. This was requested in #126 I think. Pull requests welcome!
