### ISSUE TITLE
Badges links should be updated

### ISSUE THREAD

**Issue by scls19fr** [TabViewer/tabview#145]
Hello,

since tabview is now part of TabViewer GH org badges links should be updated.
Some setup for continuous integration is also required (Sourcegraph also).

Kind regards

**Comment by firecat53** [comment]
Badge links updated. What do you mean by 'setup for continuous integration'?

**Comment by scls19fr** [comment]
A `.travis.yml` file and https://travis-ci.org/TabViewer/tabview must be enabled.
Which is the case now. So I'm closing
