### ISSUE TITLE
Auto Fit Column Width?

### ISSUE THREAD

**Issue by nickos556** [TabViewer/tabview#148]
Hey guys, great utility! Is there a way to auto fit column widths? E.g. if I have 3 columns in a csv file {a,b,c}, tabview makes all my columns the same width even though a is 20 characters wide and b 7 c are 5 characters each.

thanks

**Comment by firecat53** [comment]
It will not auto-fit to the window size. You can:

- Set columns all the same width
- Set columns to different width manually
- Toggle between variable widths calculated using the column max or column mode.

**Comment by wavexx** [comment]
On Wed, Apr 26 2017, Scott Hansen wrote:
> * Toggle between variable widths calculated using the column max or
> column mode.

I think this is what the OP intended: just press 'c' twice to maximize
all columns, or use ``--width max`` on the command line.

**Comment by nickos556** [comment]
Pressing 'c' twice works great, thank you!
