### ISSUE TITLE
Support in R

### ISSUE THREAD

**Issue by statquant** [TabViewer/tabview#157]
Hello, thanks for this very nice tool !
I was wondering if you would consider adding a R support the same way you did in python.

```
R> library(data.table)
R> data = fread('myFile.csv') # fread automagically detect separators ... 
R> library(tabview) # this could be a package
R> tabview(data) #would show the data in tabview
```

**Comment by wavexx** [comment]
On Wed, Apr 11 2018, statquant wrote:
> Hello, thanks for this very nice tool ! I was wondering if you would
> consider adding a R support the same way you did in python.

This probably would be an almost-complete reimplementation.
And knowing R, it probably would need a mixture of R and a lower-level C
extension.

Did you try to look into CRAN already?

**Comment by statquant** [comment]
Hello, sorry I did not realize this was a python project, and though that was a C++ project.
In the former case that would have been fairly vanilla given how easy it is to integrate C++ libs in R.
I did not find anything looking like tabview as a R package, there is a built in viewer in Rstudio though.
Sorry for the noob question, I'll stay with the command line tool.
